# Site settings
title: Estadística, Datos y Análisis
header-img: img/portada1.jpg
email: achirino@aru.org.bo
description: Buscando generar cultura estadística, una mirada hacia la calidad del dato y el uso responsable de información para la generación de políticas públicas
baseurl: ""
url: "http://yourdomain.com"
twitter_username: AlvaroChirinoG
github_username:  AlvaroLimber
facebook_username:  alvarolimber.chirinogutierrez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
